export const OS_STATES = Object.freeze({
  POWER_OFF: "POWER_OFF",
  BOOTING: "BOOTING",
  DESKTOP_READY: "DESKTOP_READY",
  SHUTDOWN_INIT: "SHUTDOWN_INIT",
  SHUTTING_DOWN: "SHUTTING_DOWN",
});

export const ALLOWED_TRANSITIONS = Object.freeze({
  [OS_STATES.POWER_OFF]: [OS_STATES.BOOTING],
  [OS_STATES.BOOTING]: [OS_STATES.DESKTOP_READY],
  [OS_STATES.DESKTOP_READY]: [OS_STATES.SHUTDOWN_INIT],
  [OS_STATES.SHUTDOWN_INIT]: [OS_STATES.SHUTTING_DOWN],
  [OS_STATES.SHUTTING_DOWN]: [OS_STATES.POWER_OFF],
});
